export type LintSuggestion = {
  code: string;
  message: string;
  fixHint?: string;
};

export function renderLintSuggestions(suggestions: LintSuggestion[]): string[] {
  return suggestions.map((item) => {
    const suffix = item.fixHint ? ` ${item.fixHint}` : "";
    return `- [${item.code}] ${item.message}${suffix}`;
  });
}

export const TASK_LINT_CODES = {
  DUPLICATE_ID: "TASK_DUPLICATE_ID",
  IN_PROGRESS_OWNER_EMPTY: "TASK_IN_PROGRESS_OWNER_EMPTY",
  DONE_LINKS_MISSING: "TASK_DONE_LINKS_MISSING",
  BLOCKED_SUMMARY_EMPTY: "TASK_BLOCKED_SUMMARY_EMPTY",
  UPDATED_AT_INVALID: "TASK_UPDATED_AT_INVALID",
  ROADMAP_REFS_EMPTY: "TASK_ROADMAP_REFS_EMPTY",
  OUTSIDE_MARKER: "TASK_OUTSIDE_MARKER",
  LINK_TARGET_MISSING: "TASK_LINK_TARGET_MISSING",
  HOOK_FILE_MISSING: "TASK_HOOK_FILE_MISSING",
  FILTER_EMPTY: "TASK_FILTER_EMPTY",
  CONTEXT_HOOK_HEAD_MISSING: "TASK_CONTEXT_HOOK_HEAD_MISSING",
  CONTEXT_HOOK_FOOTER_MISSING: "TASK_CONTEXT_HOOK_FOOTER_MISSING",
  // Spec v1.1.0 - Blocker Categorization
  BLOCKED_WITHOUT_BLOCKER: "TASK_BLOCKED_WITHOUT_BLOCKER",
  BLOCKER_TYPE_INVALID: "TASK_BLOCKER_TYPE_INVALID",
  BLOCKER_DESCRIPTION_EMPTY: "TASK_BLOCKER_DESCRIPTION_EMPTY",
  IN_PROGRESS_WITHOUT_SUBSTATE: "TASK_IN_PROGRESS_WITHOUT_SUBSTATE",
  SUBSTATE_PHASE_INVALID: "TASK_SUBSTATE_PHASE_INVALID",
  SUBSTATE_CONFIDENCE_INVALID: "TASK_SUBSTATE_CONFIDENCE_INVALID",
} as const;

export const ROADMAP_LINT_CODES = {
  IDS_EMPTY: "ROADMAP_IDS_EMPTY",
  TASKS_EMPTY: "ROADMAP_TASKS_EMPTY",
  TASK_REFS_EMPTY: "ROADMAP_TASK_REFS_EMPTY",
  UNKNOWN_REFS: "ROADMAP_UNKNOWN_REFS",
  ZERO_LINKED_TASKS: "ROADMAP_ZERO_LINKED_TASKS",
  CONTEXT_RELATED_TASKS_EMPTY: "ROADMAP_CONTEXT_RELATED_TASKS_EMPTY",
} as const;

export const PROJECT_LINT_CODES = {
  TASKS_FILE_MISSING: "PROJECT_TASKS_FILE_MISSING",
} as const;
