export const TASK_LINT_CODES = {
  DUPLICATE_ID: "TASK_DUPLICATE_ID",
  IN_PROGRESS_OWNER_EMPTY: "TASK_IN_PROGRESS_OWNER_EMPTY",
  DONE_LINKS_MISSING: "TASK_DONE_LINKS_MISSING",
  BLOCKED_SUMMARY_EMPTY: "TASK_BLOCKED_SUMMARY_EMPTY",
  UPDATED_AT_INVALID: "TASK_UPDATED_AT_INVALID",
  ROADMAP_REFS_EMPTY: "TASK_ROADMAP_REFS_EMPTY",
  OUTSIDE_MARKER: "TASK_OUTSIDE_MARKER",
  LINK_TARGET_MISSING: "TASK_LINK_TARGET_MISSING",
  HOOK_FILE_MISSING: "TASK_HOOK_FILE_MISSING",
  FILTER_EMPTY: "TASK_FILTER_EMPTY",
  CONTEXT_HOOK_HEAD_MISSING: "TASK_CONTEXT_HOOK_HEAD_MISSING",
  CONTEXT_HOOK_FOOTER_MISSING: "TASK_CONTEXT_HOOK_FOOTER_MISSING",
} as const;

export const ROADMAP_LINT_CODES = {
  IDS_EMPTY: "ROADMAP_IDS_EMPTY",
  TASKS_EMPTY: "ROADMAP_TASKS_EMPTY",
  TASK_REFS_EMPTY: "ROADMAP_TASK_REFS_EMPTY",
  UNKNOWN_REFS: "ROADMAP_UNKNOWN_REFS",
  ZERO_LINKED_TASKS: "ROADMAP_ZERO_LINKED_TASKS",
  CONTEXT_RELATED_TASKS_EMPTY: "ROADMAP_CONTEXT_RELATED_TASKS_EMPTY",
} as const;

export const PROJECT_LINT_CODES = {
  TASKS_FILE_MISSING: "PROJECT_TASKS_FILE_MISSING",
} as const;
