import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js"
import { z } from "zod"

function asUserPrompt(text: string) {
  return {
    messages: [
      {
        role: "user" as const,
        content: {
          type: "text" as const,
          text,
        },
      },
    ],
  }
}

export function registerExecuteTaskWorkflowPrompt(server: McpServer): void {
  server.registerPrompt(
    "executeTaskWorkflow",
    {
      title: "Execute Task Workflow",
      description: "Primary execution prompt: select one task, execute, and verify evidence consistency",
      argsSchema: {
        projectPath: z.string().optional(),
        taskId: z.string().optional(),
      },
    },
    async ({ projectPath, taskId }) => {
      const taskEntry = taskId && projectPath
        ? `1) Run taskContext(projectPath="${projectPath}", taskId="${taskId}").`
        : "1) Run taskNext().";

      const text = [
        "# Execute Task Workflow",
        "",
        "You are a Projitive task execution assistant. Here is the complete workflow:",
        "",
        "## Step 1: Get the Task",
        "",
        taskEntry,
        "",
        "## Step 2: Understand the Task",
        "",
        "After getting task context, read carefully:",
        "",
        "### Suggested Read Order",
        "Read each file in order:",
        "- Note content and location of each file",
        "- Understand task background and motivation",
        "- Identify task acceptance criteria",
        "- Look for related design decisions",
        "",
        "### Evidence",
        "- Candidate Files - Related file list",
        "- Reference Locations - Where TASK/ROADMAP IDs appear",
        "",
        "### Lint Suggestions",
        "Resolve any warnings before starting task execution.",
        "",
        "## Step 3: Execute the Task",
        "",
        "### Status Management",
        "",
        "| Current Status | Next Step | Description |",
        "|----------------|-----------|-------------|",
        "| TODO | \u2192 IN_PROGRESS | When starting execution |",
        "| IN_PROGRESS | \u2192 DONE | When task is complete |",
        "| IN_PROGRESS | \u2192 BLOCKED | When blocked |",
        "| BLOCKED | \u2192 TODO | When blocker is resolved |",
        "",
        "### Execution Steps",
        "",
        "1. **Prepare (if status is TODO)",
        "   - Call `taskUpdate()` to change status to IN_PROGRESS",
        "   - Set owner (if empty)",
        "   - Fill subState (optional, Spec v1.1.0)",
        "",
        "2. **Execute task content**",
        "   - Only edit files under .projitive/",
        "   - tasks.md - Update task status and metadata",
        "   - designs/*.md - Add or update design documents",
        "   - reports/*.md - Create execution reports",
        "   - roadmap.md - Update roadmap (if needed)",
        "",
        "3. **Create execution report**",
        "   - Create new report file in reports/ directory",
        "   - Record what changes were made",
        "   - Record why changes were made",
        "   - Record verification results",
        "",
        "4. **Complete task (if status is IN_PROGRESS)",
        "   - Confirm all acceptance criteria are met",
        "   - Call `taskUpdate()` to change status to DONE",
        "   - Update updatedAt timestamp",
        "",
        "## Step 4: Verify Changes",
        "",
        "After execution:",
        "",
        "1. **Re-run taskContext()",
        "   - Confirm task status updated correctly",
        "   - Confirm updatedAt timestamp updated",
        "",
        "2. **Check reference consistency",
        "   - Confirm all TASK/ROADMAP IDs still valid",
        "   - Confirm no broken links in Reference Locations",
        "",
        "3. **Check Lint Suggestions",
        "   - Confirm no new warnings",
        "   - If there are warnings, resolve them first",
        "",
        "4. **Continue to next task (optional)",
        "   - Call `taskNext()` for next task",
        "   - Repeat above workflow",
        "",
        "## Special Cases",
        "",
        "### Case 1: Encountered a blocker",
        "",
        "If unable to continue task execution:",
        "1. Call `taskUpdate()` to change status to BLOCKED",
        "2. Fill blocker field (Spec v1.1.0):",
        "   - type: Blocker type (dependency/missing-info/technical-debt/other)",
        "   - description: Blocker description",
        "   - relatedLinks: Related links (optional)",
        "3. Create a new TODO task to resolve blocker",
        "",
        "### Case 2: No actionable tasks",
        "",
        "If taskNext() returns empty:",
        "1. Call `projectContext()` to recheck project state",
        "2. Read design documents in designs/ directory",
        "3. Create 1-3 new TODO tasks",
        "",
        "### Case 3: Need to initialize governance",
        "",
        "If .projitive directory does not exist:",
        "1. Call `projectInit(projectPath=\"<project-dir>\")`",
        "2. Then restart",
        "",
        "## Hard Rules (NEVER violate)",
        "",
        "1. **NEVER modify TASK/ROADMAP IDs**",
        "   - Keep them immutable once assigned",
        "   - If you need to reference, keep them as-is",
        "",
        "2. **Every status transition must have report evidence**",
        "   - TODO \u2192 IN_PROGRESS: Report not required",
        "   - IN_PROGRESS \u2192 DONE: Report REQUIRED",
        "   - IN_PROGRESS \u2192 BLOCKED: Report recommended to explain blocker",
        "",
        "3. **Only edit files under .projitive/**",
        "   - Unless task scope explicitly requires modifying other files",
        "   - Any non-governance file edits must be explained in task summary",
        "",
        "4. **Always verify after updates**",
        "   - After every taskUpdate() call",
        "   - Re-run taskContext()",
        "   - Confirm reference consistency",
        "",
        "5. **Keep updatedAt in sync**",
        "   - Every time you update a task",
        "   - Must update updatedAt to current time (ISO 8601 format)",
      ].join("\n")

      return asUserPrompt(text)
    }
  )
}
