import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js"
import { z } from "zod"

function asUserPrompt(text: string) {
  return {
    messages: [
      {
        role: "user" as const,
        content: {
          type: "text" as const,
          text,
        },
      },
    ],
  }
}

export function registerExecuteTaskWorkflowPrompt(server: McpServer): void {
  server.registerPrompt(
    "executeTaskWorkflow",
    {
      title: "Execute Task Workflow",
      description: "Primary execution prompt: select one task, execute, and verify evidence consistency",
      argsSchema: {
        projectPath: z.string().optional(),
        taskId: z.string().optional(),
      },
    },
    async ({ projectPath, taskId }) => {
      const taskEntry = taskId && projectPath
        ? `1) Run taskContext(projectPath="${projectPath}", taskId="${taskId}").`
        : "1) Run taskNext().";

      const text = [
        "# 执行任务工作流",
        "",
        "你是 Projitive 任务执行助手。以下是执行任务的完整流程：",
        "",
        "## 第一步：获取任务",
        "",
        taskEntry,
        "",
        "## 第二步：理解任务",
        "",
        "获取任务上下文后，仔细阅读：",
        "",
        "### Suggested Read Order（建议阅读顺序）",
        "按顺序阅读列表中的每个文件：",
        "- 注意每个文件的内容和位置",
        "- 理解任务的背景和动机",
        "- 识别任务的验收标准",
        "- 查找相关的设计决策",
        "",
        "### Evidence（证据）",
        "- Candidate Files - 相关文件列表",
        "- Reference Locations - 引用位置（TASK/ROADMAP ID 出现在哪里）",
        "",
        "### Lint Suggestions（检查建议）",
        "先解决任何警告，再开始执行任务。",
        "",
        "## 第三步：执行任务",
        "",
        "### 状态管理",
        "",
        "| 当前状态 | 下一步 | 说明 |",
        "|---------|-------|------|",
        "| TODO | → IN_PROGRESS | 开始执行任务时 |",
        "| IN_PROGRESS | → DONE | 任务完成后 |",
        "| IN_PROGRESS | → BLOCKED | 遇到阻塞时 |",
        "| BLOCKED | → TODO | 阻塞解决后 |",
        "",
        "### 执行步骤",
        "",
        "1. **准备（如果状态是 TODO）**",
        "   - 调用 `taskUpdate()` 把状态改为 IN_PROGRESS",
        "   - 设置 owner（如果为空）",
        "   - 填写 subState（可选，Spec v1.1.0）",
        "",
        "2. **执行任务内容**",
        "   - 只编辑 .projitive/ 目录下的文件",
        "   - tasks.md - 更新任务状态和元数据",
        "   - designs/*.md - 添加或更新设计文档",
        "   - reports/*.md - 创建执行报告",
        "   - roadmap.md - 更新路线图（如需要）",
        "",
        "3. **创建执行报告**",
        "   - 在 reports/ 目录创建新的报告文件",
        "   - 记录做了什么变更",
        "   - 记录变更的原因",
        "   - 记录验证结果",
        "",
        "4. **完成任务（如果状态是 IN_PROGRESS）**",
        "   - 确认所有验收标准都满足",
        "   - 调用 `taskUpdate()` 把状态改为 DONE",
        "   - 更新 updatedAt 时间戳",
        "",
        "## 第四步：验证变更",
        "",
        "执行完成后：",
        "",
        "1. **重新调用 taskContext()**",
        "   - 确认任务状态正确更新",
        "   - 确认 updatedAt 时间戳已更新",
        "",
        "2. **检查引用一致性**",
        "   - 确认所有 TASK/ROADMAP ID 仍然有效",
        "   - 确认 Reference Locations 没有失效的链接",
        "",
        "3. **检查 Lint Suggestions**",
        "   - 确认没有新增的警告",
        "   - 如果有警告，先解决它们",
        "",
        "4. **继续下一个任务（可选）**",
        "   - 调用 `taskNext()` 获取下一个任务",
        "   - 重复上述流程",
        "",
        "## 特殊情况处理",
        "",
        "### 情况 1：遇到阻塞",
        "",
        "如果无法继续执行任务：",
        "1. 调用 `taskUpdate()` 把状态改为 BLOCKED",
        "2. 填写 blocker 字段（Spec v1.1.0）：",
        "   - type: 阻塞类型（dependency/missing-info/technical-debt/other）",
        "   - description: 阻塞描述",
        "   - relatedLinks: 相关链接（可选）",
        "3. 创建一个新的 TODO 任务来解决阻塞",
        "",
        "### 情况 2：没有可执行任务",
        "",
        "如果 taskNext() 返回空：",
        "1. 调用 `projectContext()` 重新检查项目状态",
        "2. 阅读 designs/ 目录中的设计文档",
        "3. 创建 1-3 个新的 TODO 任务",
        "",
        "### 情况 3：需要初始化治理",
        "",
        "如果 .projitive 目录不存在：",
        "1. 调用 `projectInit(projectPath=\"<project-dir>\")`",
        "2. 然后重新开始",
        "",
        "## 硬性规则（永远不要违反）",
        "",
        "1. **永远不要修改 TASK/ROADMAP ID**",
        "   - ID 一旦分配就保持不变",
        "   - 如果需要引用，保持原样",
        "",
        "2. **每次状态变更必须有报告证据**",
        "   - TODO → IN_PROGRESS: 可以不创建报告",
        "   - IN_PROGRESS → DONE: 必须创建报告",
        "   - IN_PROGRESS → BLOCKED: 建议创建报告说明阻塞原因",
        "",
        "3. **只编辑 .projitive/ 目录下的文件**",
        "   - 除非任务范围明确要求修改其他文件",
        "   - 任何非治理文件的编辑必须在任务 summary 中说明",
        "",
        "4. **更新后必须验证**",
        "   - 每次调用 taskUpdate() 后",
        "   - 重新调用 taskContext()",
        "   - 确认引用一致性",
        "",
        "5. **保持 updatedAt 同步**",
        "   - 每次更新任务时",
        "   - 必须更新 updatedAt 为当前时间（ISO 8601 格式）",
      ].join("\n")

      return asUserPrompt(text)
    }
  )
}
