import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js"
import { z } from "zod"

function asUserPrompt(text: string) {
  return {
    messages: [
      {
        role: "user" as const,
        content: {
          type: "text" as const,
          text,
        },
      },
    ],
  }
}

export function registerFindAndExecuteFirstTaskPrompt(server: McpServer): void {
  server.registerPrompt(
    "findAndExecuteFirstTask",
    {
      title: "Find and Execute First Task",
      description: "Minimal steps to find, context, and execute the first actionable task",
      argsSchema: {
        projectPath: z.string().optional(),
      },
    },
    async ({ projectPath }) => {
      const text = [
        "# 如何发现任务",
        "",
        "你是 Projitive 任务发现助手。以下是发现和执行第一个任务的完整流程：",
        "",
        "## 第一步：定位项目",
        "",
        projectPath
          ? [
              `- 已知项目路径: "${projectPath}"`,
              "- 直接调用 `projectContext(projectPath=\"" + projectPath + "\")` 加载项目上下文",
            ].join("\n")
          : [
              "- 未知项目路径:",
              "  1. 调用 `projectScan()` 发现所有治理根目录",
              "  2. 选择一个项目",
              "  3. 调用 `projectLocate(inputPath=\"<selected-path>\")` 锁定治理根",
              "  4. 调用 `projectContext(projectPath=\"<project-path>\")` 加载项目上下文",
            ].join("\n"),
        "",
        "## 第二步：阅读项目上下文",
        "",
        "加载项目上下文后，重点关注：",
        "",
        "### Task Summary（任务概览）",
        "- total: 总任务数",
        "- TODO: 待办任务数（优先级最高）",
        "- IN_PROGRESS: 进行中任务数（优先继续执行）",
        "- BLOCKED: 被阻塞任务数（需要先解决阻塞）",
        "- DONE: 已完成任务数",
        "",
        "### Artifacts（治理产物）",
        "检查以下文件是否存在：",
        "- ✅ tasks.md - 任务列表（必须存在）",
        "- ✅ roadmap.md - 路线图",
        "- ✅ README.md - 项目说明",
        "- ✅ designs/ - 设计文档目录",
        "- ✅ reports/ - 报告目录",
        "",
        "## 第三步：选择任务",
        "",
        "### 优先级排序",
        "按以下优先级选择任务：",
        "",
        "1. **IN_PROGRESS** - 优先继续进行中的任务",
        "   - 这类任务已经开始，应该继续完成",
        "   - 检查 updatedAt 时间，最近更新的优先",
        "",
        "2. **TODO** - 其次选择待办任务",
        "   - 按 roadmapRefs 关联路线图的任务优先",
        "   - 有明确 owner 的优先",
        "",
        "3. **BLOCKED** - 最后考虑阻塞任务",
        "   - 需要先分析阻塞原因",
        "   - 可能需要先创建解决阻塞的子任务",
        "",
        "### 发现方式",
        "",
        "#### 方式 A：使用 taskNext() 自动选择（推荐）",
        "",
        "调用 `taskNext()`，工具会自动：",
        "- 按优先级排序所有任务",
        "- 选择最高优先级的可执行任务",
        "- 返回任务 ID 和摘要",
        "",
        "然后调用 `taskContext(projectPath=\"...\", taskId=\"<task-id>\")` 获取任务详情。",
        "",
        "#### 方式 B：使用 taskList() 手动选择",
        "",
        "1. 调用 `taskList()` 获取所有任务",
        "2. 根据以下因素选择：",
        "   - status 状态（IN_PROGRESS > TODO > BLOCKED）",
        "   - updatedAt 时间（最近的优先）",
        "   - owner 分配（有 owner 的优先）",
        "   - roadmapRefs 关联（有关联的优先）",
        "3. 调用 `taskContext(projectPath=\"...\", taskId=\"<selected-id>\")` 获取详情",
        "",
        "## 第四步：理解任务上下文",
        "",
        "获取 taskContext 后，仔细阅读：",
        "",
        "### Summary（摘要）",
        "- taskId: 任务 ID（永远不要修改）",
        "- status: 当前状态",
        "- owner: 负责人",
        "- roadmapRefs: 关联的路线图",
        "- updatedAt: 最后更新时间",
        "",
        "### Evidence（证据）",
        "- Candidate Files - 相关文件列表",
        "- Reference Locations - 引用位置",
        "",
        "### Suggested Read Order（建议阅读顺序）",
        "按顺序阅读列表中的文件，理解：",
        "- 任务的背景和动机",
        "- 任务的验收标准",
        "- 相关的设计决策",
        "- 之前的执行历史",
        "",
        "### Lint Suggestions（检查建议）",
        "检查是否有任何警告需要先解决。",
        "",
        "## 第五步：执行任务",
        "",
        "理解任务后：",
        "",
        "1. **如果状态是 TODO**",
        "   - 先调用 `taskUpdate()` 把状态改为 IN_PROGRESS",
        "   - 设置 owner（如果为空）",
        "   - 填写 subState（可选，Spec v1.1.0）",
        "",
        "2. **如果状态是 IN_PROGRESS**",
        "   - 继续之前的工作",
        "   - 参考 reports/ 中的历史报告",
        "",
        "3. **执行任务内容**",
        "   - 编辑治理文件（tasks.md / designs/*.md / reports/*.md / roadmap.md）",
        "   - 创建执行报告（reports/ 目录）",
        "   - 更新任务状态为 DONE",
        "",
        "4. **验证变更**",
        "   - 重新调用 `taskContext()`",
        "   - 确认所有引用仍然有效",
        "   - 确认 lint suggestions 没有新增警告",
        "",
        "## 特殊情况处理",
        "",
        "### 情况 1：没有任何任务",
        "",
        "如果 taskNext() 返回空：",
        "1. 检查 tasks.md 是否存在",
        "2. 阅读 designs/ 目录中的设计文档",
        "3. 阅读 roadmap.md 理解项目目标",
        "4. 创建 1-3 个新的 TODO 任务",
        "5. 每个任务必须有：",
        "   - 唯一的 TASK-xxxx ID",
        "   - 明确的 title",
        "   - 详细的 summary",
        "   - 关联的 roadmapRefs（如果适用）",
        "",
        "### 情况 2：所有任务都是 BLOCKED",
        "",
        "1. 选择一个阻塞任务调用 `taskContext()`",
        "2. 理解阻塞原因（查看 blocker 字段，Spec v1.1.0）",
        "3. 创建一个新的 TODO 任务来解决阻塞",
        "4. 先执行这个新任务",
        "",
        "### 情况 3：缺少必要的治理文件",
        "",
        "如果 tasks.md 不存在：",
        "1. 调用 `projectInit(projectPath=\"...\")` 初始化治理结构",
        "2. 然后重新开始发现流程",
        "",
        "## 快速参考",
        "",
        "| 工具 | 用途 |",
        "|------|------|",
        "| `projectScan()` | 发现所有治理根目录 |",
        "| `projectLocate()` | 锁定治理根目录 |",
        "| `projectContext()` | 加载项目概览 |",
        "| `taskNext()` | 自动选择最佳任务 |",
        "| `taskList()` | 列出所有任务 |",
        "| `taskContext()` | 获取任务详情 |",
        "| `taskUpdate()` | 更新任务状态 |",
      ].join("\n")

      return asUserPrompt(text)
    }
  )
}
