import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js"
import { z } from "zod"

function asUserPrompt(text: string) {
  return {
    messages: [
      {
        role: "user" as const,
        content: {
          type: "text" as const,
          text,
        },
      },
    ],
  }
}

export function registerFindAndExecuteFirstTaskPrompt(server: McpServer): void {
  server.registerPrompt(
    "findAndExecuteFirstTask",
    {
      title: "Find and Execute First Task",
      description: "Minimal steps to find, context, and execute the first actionable task",
      argsSchema: {
        projectPath: z.string().optional(),
      },
    },
    async ({ projectPath }) => {
      const text = [
        "# How to Discover Tasks",
        "",
        "You are a Projitive task discovery assistant. Here is the complete workflow to discover and execute your first task:",
        "",
        "## Step 1: Locate the Project",
        "",
        projectPath
          ? [
              `- Known project path: "${projectPath}"`,
              "- Call `projectContext(projectPath=\"" + projectPath + "\")` directly to load project context",
            ].join("\n")
          : [
              "- Unknown project path:",
              "  1. Call `projectScan()` to discover all governance roots",
              "  2. Select a project",
              "  3. Call `projectLocate(inputPath=\"<selected-path>\")` to lock governance root",
              "  4. Call `projectContext(projectPath=\"<project-path>\")` to load project context",
            ].join("\n"),
        "",
        "## Step 2: Read Project Context",
        "",
        "After loading project context, focus on:",
        "",
        "### Task Summary",
        "- total: Total tasks",
        "- TODO: Pending tasks (highest priority)",
        "- IN_PROGRESS: In-progress tasks (priority to continue)",
        "- BLOCKED: Blocked tasks (need to resolve first)",
        "- DONE: Completed tasks",
        "",
        "### Artifacts",
        "Check if these files exist:",
        "- \u2705 tasks.md - Task list (required)",
        "- \u2705 roadmap.md - Roadmap",
        "- \u2705 README.md - Project description",
        "- \u2705 designs/ - Design documents directory",
        "- \u2705 reports/ - Reports directory",
        "",
        "## Step 3: Select a Task",
        "",
        "### Priority Order",
        "Select tasks in this priority order:",
        "",
        "1. **IN_PROGRESS** - Priority to continue in-progress tasks first",
        "   - These tasks have already started, should continue to finish",
        "   - Check updatedAt time, most recent first",
        "",
        "2. **TODO** - Next select pending tasks",
        "   - Tasks with roadmapRefs first",
        "   - Tasks with explicit owner first",
        "",
        "3. **BLOCKED** - Last consider blocked tasks",
        "   - Need to analyze blocker reason first",
        "   - May need to create sub-task to resolve blocker",
        "",
        "### Discovery Methods",
        "",
        "#### Method A: Auto-select with taskNext() (Recommended)",
        "",
        "Call `taskNext()`, the tool will automatically:",
        "- Sort all tasks by priority",
        "- Select highest-priority actionable task",
        "- Return task ID and summary",
        "",
        "Then call `taskContext(projectPath=\"...\", taskId=\"<task-id>\")` for task details.",
        "",
        "#### Method B: Manual select with taskList()",
        "",
        "1. Call `taskList()` to get all tasks",
        "2. Select based on these factors:",
        "   - status (IN_PROGRESS > TODO > BLOCKED)",
        "   - updatedAt time (most recent first)",
        "   - owner assigned (with owner first)",
        "   - roadmapRefs (with refs first)",
        "3. Call `taskContext(projectPath=\"...\", taskId=\"<selected-id>\")` for details",
        "",
        "## Step 4: Understand Task Context",
        "",
        "After getting taskContext, read carefully:",
        "",
        "### Summary",
        "- taskId: Task ID (NEVER modify this)",
        "- status: Current status",
        "- owner: Assignee",
        "- roadmapRefs: Related roadmap",
        "- updatedAt: Last updated time",
        "",
        "### Evidence",
        "- Candidate Files - Related file list",
        "- Reference Locations - Reference locations",
        "",
        "### Suggested Read Order",
        "Read files in order, understand:",
        "- Task background and motivation",
        "- Task acceptance criteria",
        "- Related design decisions",
        "- Previous execution history",
        "",
        "### Lint Suggestions",
        "Check if any warnings need to be resolved first.",
        "",
        "## Step 5: Execute the Task",
        "",
        "After understanding the task:",
        "",
        "1. **If status is TODO",
        "   - First call `taskUpdate()` to change status to IN_PROGRESS",
        "   - Set owner (if empty)",
        "   - Fill subState (optional, Spec v1.1.0)",
        "",
        "2. **If status is IN_PROGRESS",
        "   - Continue previous work",
        "   - Reference history reports in reports/",
        "",
        "3. **Execute task content**",
        "   - Edit governance files (tasks.md / designs/*.md / reports/*.md / roadmap.md)",
        "   - Create execution report (reports/ directory)",
        "   - Update task status to DONE",
        "",
        "4. **Verify changes**",
        "   - Re-run `taskContext()`",
        "   - Confirm all references still valid",
        "   - Confirm no new lint suggestions",
        "",
        "## Special Cases",
        "",
        "### Case 1: No tasks at all",
        "",
        "If taskNext() returns empty:",
        "1. Check if tasks.md exists",
        "2. Read design documents in designs/ directory",
        "3. Read roadmap.md to understand project goals",
        "4. Create 1-3 new TODO tasks",
        "5. Each task must have:",
        "   - Unique TASK-xxxx ID",
        "   - Clear title",
        "   - Detailed summary",
        "   - Linked roadmapRefs (if applicable)",
        "",
        "### Case 2: All tasks are BLOCKED",
        "",
        "1. Select one blocked task and call `taskContext()`",
        "2. Understand blocker reason (check blocker field, Spec v1.1.0)",
        "3. Create a new TODO task to resolve blocker",
        "4. Execute this new task first",
        "",
        "### Case 3: Missing required governance files",
        "",
        "If tasks.md does not exist:",
        "1. Call `projectInit(projectPath=\"...\")` to initialize governance structure",
        "2. Then restart discovery flow",
        "",
        "## Quick Reference",
        "",
        "| Tool | Purpose |",
        "|------|---------|",
        "| `projectScan()` | Discover all governance roots |",
        "| `projectLocate()` | Lock governance root |",
        "| `projectContext()` | Load project overview |",
        "| `taskNext()` | Auto-select best task |",
        "| `taskList()` | List all tasks |",
        "| `taskContext()` | Get task details |",
        "| `taskUpdate()` | Update task status |",
      ].join("\n")

      return asUserPrompt(text)
    }
  )
}
