import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { z } from 'zod'

function asUserPrompt(text: string) {
  return {
    messages: [
      {
        role: 'user' as const,
        content: {
          type: 'text' as const,
          text,
        },
      },
    ],
  }
}

export function registerQuickStartPrompt(server: McpServer): void {
  server.registerPrompt(
    'quickStart',
    {
      title: 'Quick Start',
      description: 'Complete workflow to discover project, load context, and start task execution',
      argsSchema: {
        projectPath: z.string().optional(),
      },
    },
    async ({ projectPath }) => {
      const text = [
        '# How to Govern a Project',
        '',
        'You are a Projitive governance assistant. Here is the complete workflow:',
        '',
        '## Step 1: Discover the Project',
        '',
        projectPath
          ? [
              `- Known project path: "${projectPath}"`,
              '- Call `projectContext(projectPath="' + projectPath + '")` directly to load project overview',
            ].join('\n')
          : [
              '- Unknown project path:',
              '  1. Call `projectScan()` to discover all governance roots',
              '  2. Select a target project',
              '  3. Call `projectLocate(inputPath="<selected-path>")` to lock governance root',
              '  4. Call `projectContext(projectPath="<project-path>")` to load project overview',
            ].join('\n'),
        '',
        '## Step 2: Understand the Project',
        '',
        'After loading project context, read these resources:',
        '- projitive://governance/workspace - Project overview',
        '- projitive://governance/tasks - Current task pool',
        '- projitive://governance/roadmap - Project roadmap',
        '- projitive://designs/* - Design documents',
        '',
        '## Step 3: Discover Tasks',
        '',
        'Two ways to discover tasks:',
        '',
        '### Option A: Auto-select (Recommended)',
        'Call `taskNext()` to get highest-priority actionable task.',
        'If no actionable tasks are returned and roadmap has active goals, analyze roadmap context and create 1-3 TODO tasks via `taskCreate()`.',
        'Then call `taskNext()` again to re-rank.',
        '',
        '### Option B: Manual select',
        '1. Call `taskList()` to list all tasks',
        '2. Select a task based on status and priority',
        '3. Call `taskContext(projectPath="...", taskId="...")` for details',
        '',
        '## Step 4: Execute the Task',
        '',
        'After getting task context:',
        '1. Read evidence links in Suggested Read Order',
        '2. Understand task requirements and acceptance criteria',
        '3. Write governance source via tools (`taskCreate` / `taskUpdate` / `roadmapCreate` / `roadmapUpdate`) instead of editing tasks.md/roadmap.md directly',
        '4. Update docs (`designs/` / `reports/`) as required by evidence',
        '4.5. Before closing the task, check whether `designs/core/architecture.md`, `designs/core/code-style.md`, or `designs/core/ui-style.md` need updates',
        '5. taskCreate/taskUpdate/roadmapCreate/roadmapUpdate will auto-sync corresponding markdown views',
        '6. Update task status:',
        '   - TODO → IN_PROGRESS (when starting execution)',
        '   - IN_PROGRESS → DONE (when completed)',
        '   - IN_PROGRESS → BLOCKED (when blocked)',
        '7. Re-run taskContext() to verify changes',
        '',
        '## Autonomous Operating Loop',
        '',
        'Keep this loop while high-value actionable tasks exist:',
        '1. Discover: `taskNext()` - Select highest-priority task',
        '2. Execute: perform work + update governance store (.projitive) + docs',
        '3. Verify: `taskContext()` - Confirm changes and consistency',
        '4. Re-prioritize: `taskNext()` - Update priority and select next',
        '',
        '**When to Stop or Pause:**',
        '',
        '**Stop Reason 1: Task is BLOCKED and needs external action**',
        '- Blocker must have: type, description, blockingEntity (if applicable), unblockCondition (if applicable)',
        '- Cannot continue work until blocker is actually resolved (not just "in progress")',
        '- Examples:',
        '  - internal_dependency: dependent TASK must be DONE first',
        '  - external_dependency: external party must deliver (tracked via escalationPath)',
        '  - resource: tool/access/budget must be allocated (tracked via escalationPath)',
        '  - approval: decision-maker must sign off (tracked via blockingEntity)',
        '- **What to do next:** Follow BLOCKED guidance to unblock, then re-run `taskNext()`',
        '',
        '**Stop Reason 2: Task is DONE and all acceptance criteria are met**',
        '- Verify in `taskContext()` that all links/references are consistent',
        '- Check that report/design/roadmap evidence is properly documented',
        '- **What to do next:** Run `taskNext()` to pick the next task',
        '',
        '**Stop Reason 3: No actionable tasks (all TODO blocked or no tasks exist)**',
        '- Means: all unblocked work is complete, only blocked tasks remain OR no tasks at all',
        '- **What to do next:** Analyze blockers and roadmap, create 1-3 new TODO tasks via `taskCreate()`',
        '- Prefer creating or refreshing core-doc tasks first when `designs/core/architecture.md`, `designs/core/code-style.md`, or `designs/core/ui-style.md` are missing or stale',
        '',
        '## Special Cases',
        '',
        '### Case 1: No .projitive directory or required governance artifacts are missing',
        'Call `projectInit(projectPath="<project-dir>")` to initialize or repair governance structure.',
        '',
        '### Case 2: No actionable tasks (all TODO/IN_PROGRESS are blocked OR task count is zero)',
        '',
        '**If some tasks exist but all are BLOCKED:**',
        '1. Run `taskList()` and filter by status = BLOCKED',
        '2. For each BLOCKED task, check its blocker type:',
        '   - **internal_dependency**: Is the blocking task listed? If no, create it',
        '   - **external_dependency**: Is escalationPath defined? If no, add it',
        '   - **resource**: Is escalationPath defined for requestor? If no, add it',
        '   - **approval**: Is blockingEntity defined? If no, add it',
        '3. For each blocker with missing metadata: call `taskUpdate()` to complete it',
        '4. Select 1 BLOCKED task: follow its unblock guidance to take concrete action',
        '5. Once blocker is resolved: call `taskUpdate(..., {status: "TODO"})` to unblock',
        '6. Re-run `taskNext()` to see newly unblocked tasks',
        '',
        '**If no tasks exist at all (or only DONE tasks):**',
        '1. Review `projectContext()` to confirm task count is 0',
        '2. Read active roadmap milestones via `roadmapContext()`',
        '3. For each active milestone, derive 1-3 executable TODO tasks:',
        '   - **Clear outcome**: one-sentence done condition',
        '   - **Evidence target**: at least one artifact (report, design, readme update)',
        '   - **Small slice**: completable in one focused execution cycle',
        '   - **Roadmap link**: link to roadmap via roadmapRefs',
        '   - **Minimal dependencies**: avoid complex task chains at start',
        '4. Call `taskCreate()` for each task with complete metadata',
        '5. Re-run `taskNext()` to start executing the new tasks',
        '6. Ensure bootstrap projects include TODO tasks for project architecture, code style, and UI style docs',
        '',
        '**If roadmap is also empty:**',
        '1. Read design documents under `projitive://designs/`',
        '2. Identify next architectural milestone or feature slice',
        '3. Document in ROADMAP.md via `roadmapCreate()`',
        '4. Create corresponding TODO tasks via `taskCreate()`',
        '',
        '## Hard Rules',
        '',
        '- **NEVER modify TASK/ROADMAP IDs** - Keep them immutable once assigned',
        '- **Every status transition must have report evidence** - Create execution reports in reports/ directory',
        '- **.projitive governance store is source of truth** - tasks.md/roadmap.md are generated views and may be overwritten',
        '- **MUST use tools for task/roadmap changes** - Use taskCreate/taskUpdate/roadmapCreate/roadmapUpdate',
        '- **NEVER edit tasks.md or roadmap.md directly** - They are generated views, not writable source-of-truth',
        '- **Always verify after updates** - Re-run taskContext() to confirm reference consistency',
        '- **BLOCKED tasks require full blocker metadata** - type, description required; blockingEntity, unblockCondition, escalationPath as needed',
        '- **Every completed task should re-check core docs** - architecture.md for system changes, code-style.md for engineering conventions, ui-style.md for UI/pattern changes',
      ].join('\n')

      return asUserPrompt(text)
    }
  )
}
