import { describe, it, expect, beforeAll, afterAll, vi } from 'vitest'
import fs from 'node:fs/promises'
import path from 'node:path'
import os from 'node:os'
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { isValidRoadmapId, collectRoadmapLintSuggestions, loadRoadmapDocument, renderRoadmapMarkdown, registerRoadmapTools } from './roadmap.js'

describe('roadmap module', () => {
  let tempDir: string

  beforeAll(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'projitive-roadmap-test-'))
  })

  afterAll(async () => {
    await fs.rm(tempDir, { recursive: true, force: true })
  })

  describe('isValidRoadmapId', () => {
    it('should validate correct roadmap IDs', () => {
      expect(isValidRoadmapId('ROADMAP-0001')).toBe(true)
      expect(isValidRoadmapId('ROADMAP-1')).toBe(true)
      expect(isValidRoadmapId('ROADMAP-1234')).toBe(true)
      expect(isValidRoadmapId('ROADMAP-12345')).toBe(true)
    })

    it('should reject invalid roadmap IDs', () => {
      expect(isValidRoadmapId('roadmap-0001')).toBe(false)
      expect(isValidRoadmapId('TASK-0001')).toBe(false)
      expect(isValidRoadmapId('invalid')).toBe(false)
    })
  })

  describe('collectRoadmapLintSuggestions', () => {
    it('should return lint suggestion for empty roadmap IDs', () => {
      const suggestions = collectRoadmapLintSuggestions([], [])
      expect(suggestions.some(s => s.includes('IDS_EMPTY'))).toBe(true)
    })

    it('should return lint suggestion for empty tasks', () => {
      const suggestions = collectRoadmapLintSuggestions(['ROADMAP-0001'], [])
      expect(suggestions.some(s => s.includes('TASKS_EMPTY'))).toBe(true)
    })

    it('should return lint suggestion for tasks without roadmap refs', () => {
      const tasks = [{
        id: 'TASK-0001',
        title: 'Test Task',
        status: 'TODO' as const,
        owner: 'ai-copilot',
        summary: 'Test',
        updatedAt: '2026-01-01T00:00:00.000Z',
        links: [],
        roadmapRefs: [],
      }]
      const suggestions = collectRoadmapLintSuggestions(['ROADMAP-0001'], tasks)
      expect(suggestions.some(s => s.includes('TASK_REFS_EMPTY'))).toBe(true)
    })

    it('loads from governance store and rewrites roadmap markdown view', async () => {
      const governanceDir = path.join(tempDir, '.projitive-db')
      await fs.mkdir(governanceDir, { recursive: true })
      await fs.writeFile(path.join(governanceDir, '.projitive'), '', 'utf-8')

      const doc = await loadRoadmapDocument(governanceDir)
      expect(doc.roadmapPath.endsWith('.projitive')).toBe(true)
      expect(doc.markdownPath.endsWith('roadmap.md')).toBe(true)

      const markdown = await fs.readFile(path.join(governanceDir, 'roadmap.md'), 'utf-8')
      expect(markdown).toContain('generated from .projitive governance store')
      expect(markdown).toContain('Author: yinxulai')
      expect(markdown).toContain('Repository: https://github.com/yinxulai/projitive')
      expect(markdown).toContain('Do not edit this file manually.')
    })

    it('renders milestones in newest-first order', () => {
      const markdown = renderRoadmapMarkdown([
        { id: 'ROADMAP-0001', title: 'Older', status: 'active', updatedAt: '2026-01-01T00:00:00.000Z' },
        { id: 'ROADMAP-0002', title: 'Newer', status: 'done', updatedAt: '2026-02-01T00:00:00.000Z' },
      ])

      expect(markdown.indexOf('ROADMAP-0002')).toBeLessThan(markdown.indexOf('ROADMAP-0001'))
      expect(markdown).toContain('[x] ROADMAP-0002')
    })

    it('registers roadmapCreate tool', () => {
      const mockServer = {
        registerTool: (...args: unknown[]) => {
          void args
          return undefined
        },
      }
      const spy = vi.spyOn(mockServer, 'registerTool')

      registerRoadmapTools(mockServer as unknown as McpServer)

      expect(spy.mock.calls.some((call) => call[0] === 'roadmapCreate')).toBe(true)
    })
  })
})
